{{/*
Copyright The Linux Foundation and each contributor to LFX.
SPDX-License-Identifier: MIT
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "lfx-v2-newsletter-service.fullname" . }}
  labels:
    {{- include "lfx-v2-newsletter-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lfx-v2-newsletter-service.selectorLabels" . | nindent 4 }}
